image: docker:git

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive
  configurations: unixlike-gcc-debug unixlike-clang-debug unixlike-gcc-release unixlike-clang-release

services:
  - docker:dind

default:
  cache:
    key: docker-build-folder
    paths:
      - ci/cache
  before_script:
    - docker buildx create --name=builder-container --driver=docker-container --use --bootstrap
    - docker build --builder=builder-container --load --cache-from type=local,src=ci/cache --cache-to type=local,dest=ci/cache,compression=zstd -t stmesh-builder:latest --build-arg='VARIANT=noble' --build-arg='GCC_VER=14' --build-arg='LLVM_VER=18' --target develop .
    - docker buildx rm builder-container

compile:
  stage: build
  script:
    - |+
      for config in $configurations
      do
        ./ci/run_docker_build.sh build $config
      done
  artifacts:
    paths:
      - out

test:
  stage: test
  script:
    - |+
      for config in $configurations
      do
        ./ci/run_docker_build.sh test $config
      done
